-- Legacy migration preserved as a no-op placeholder.
-- Its original SQL was archived into:
-- prisma/migrations_archive_legacy/20260428120000_server_first_perf/migration.sql
--
-- The replayable behavior now lives in:
-- prisma/migrations/20260428000000_squashed_baseline/migration.sql
